on:
  push:
    tags: ["v*"]
  pull_request:
    branches: ["*"]

name: Build and deploy
jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Run Integration tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
